/**
 * @mailysend/ui — source-only. The consuming app's bundler compiles it, which
 * is why every relative import below carries its extension.
 *
 * Two layers live here: shadcn-shaped primitives retheme'd onto the design
 * tokens, and the components the design itself invented (`Terminal`,
 * `StatusBadge`, `ComparisonTable`, …). Only the second layer is load-bearing
 * for the product's identity; the first is deliberately unremarkable.
 */

// Primitives
export * from './components/accordion.tsx'
export * from './components/alert.tsx'
// The design's own vocabulary
export * from './components/anchor-pills.tsx'
export * from './components/avatar.tsx'
export * from './components/badge.tsx'
export * from './components/bar-row.tsx'
export * from './components/breadcrumb.tsx'
export * from './components/button.tsx'
export * from './components/calendar.tsx'
export * from './components/callout.tsx'
export * from './components/card.tsx'
export * from './components/checkbox.tsx'
export * from './components/code-tabs.tsx'
export * from './components/command.tsx'
export * from './components/command-strip.tsx'
export * from './components/comparison-table.tsx'
export * from './components/cta-band.tsx'
export * from './components/date-range-picker.tsx'
export * from './components/dialog.tsx'
export * from './components/dropdown-menu.tsx'
export * from './components/empty-state.tsx'
export * from './components/eyebrow.tsx'
export * from './components/flow.tsx'
export * from './components/gain-loss-list.tsx'
export * from './components/hairline-rule.tsx'
export * from './components/input.tsx'
export * from './components/kbd.tsx'
export * from './components/key-value.tsx'
export * from './components/label.tsx'
export * from './components/log-row.tsx'
export * from './components/metric.tsx'
export * from './components/mono-chip.tsx'
export * from './components/pagination.tsx'
export * from './components/pill.tsx'
export * from './components/popover.tsx'
export * from './components/progress.tsx'
export * from './components/radio-group.tsx'
export * from './components/scroll-area.tsx'
export * from './components/section-header.tsx'
export * from './components/select.tsx'
export * from './components/separator.tsx'
export * from './components/sheet.tsx'
export * from './components/skeleton.tsx'
export * from './components/slider.tsx'
export * from './components/stat-tile.tsx'
export * from './components/status-badge.tsx'
export * from './components/status-dot.tsx'
export * from './components/step-card.tsx'
export * from './components/switch.tsx'
export * from './components/table.tsx'
export * from './components/tabs.tsx'
export * from './components/terminal.tsx'
export * from './components/textarea.tsx'
export * from './components/toast.tsx'
export * from './components/toggle-group.tsx'
export * from './components/tooltip.tsx'
export { cn } from './lib/cn.ts'
export { useCopy } from './lib/use-copy.ts'
