import type { NormalizedEventType } from '@mailysend/contracts'
import { sha256Hex } from '@mailysend/core'

/**
 * Deterministic event identity.
 *
 * The id is derived from the event's content, not assigned. That single choice
 * removes an entire class of problem: a provider redelivering a webhook, a
 * queue redelivering a message, or two ingress paths seeing the same SNS
 * notification all produce a byte-identical id, so the duplicate collapses on
 * an `INSERT OR IGNORE` instead of needing a distributed transaction.
 *
 * The timestamp is truncated to the second on purpose. Providers re-serialise
 * timestamps between retries and sub-second precision is not stable across
 * them, so including milliseconds would make "the same event" hash differently
 * on redelivery — which is exactly what we are trying to prevent.
 */
export const eventId = (input: {
  provider: string
  providerMessageId: string | null
  type: NormalizedEventType
  recipient: string
  occurredAt: string | Date
}): Promise<string> => {
  const seconds = Math.floor(new Date(input.occurredAt).getTime() / 1000)
  return sha256Hex(
    [
      input.provider,
      input.providerMessageId ?? '',
      input.type,
      input.recipient.toLowerCase(),
      String(seconds),
    ].join('|'),
  )
}

/**
 * Opens and clicks have no provider id — they are generated by us, on a hit to
 * the tracking Worker. Their identity is the message, the recipient, the link
 * and the second, which means a double-fired pixel within the same second
 * dedupes while two genuine opens a second apart do not.
 */
export const trackingEventId = (input: {
  emailId: string
  type: 'opened' | 'clicked'
  recipient: string
  linkId?: string
  occurredAt: string | Date
}): Promise<string> =>
  sha256Hex(
    [
      'internal',
      input.emailId,
      input.type,
      input.recipient.toLowerCase(),
      input.linkId ?? '',
      String(Math.floor(new Date(input.occurredAt).getTime() / 1000)),
    ].join('|'),
  )
