/**
 * Embeds migrations/*.sql into a TypeScript module.
 *
 * Wrangler can apply migrations from disk, but neither the Worker at runtime
 * nor the one-click deploy has a filesystem to read them from — and the Node
 * runtime applies them at boot. Embedding is the only form all three can share.
 */
import { readdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const dir = join(root, 'migrations')

const files = (await readdir(dir)).filter((f) => f.endsWith('.sql')).sort()
const parts: string[] = []
for (const f of files) {
  const sql = await readFile(join(dir, f), 'utf8')
  parts.push(`  { name: ${JSON.stringify(f)}, sql: ${JSON.stringify(sql)} },`)
}

await writeFile(
  join(root, 'src/migrations.generated.ts'),
  `// Generated by packages/db/scripts/embed.ts — do not edit.\n` +
    `// Regenerate with: pnpm --filter @mailysend/db generate\n\n` +
    `export const MIGRATION_FILES: { name: string; sql: string }[] = [\n${parts.join('\n')}\n]\n`,
)

console.log(`embedded ${files.length} migration(s)`)
